# Generated by Django 3.2.7 on 2021-11-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=60)),
                ('Apellidos', models.CharField(max_length=60)),
                ('No_documento', models.IntegerField()),
                ('Direccion', models.CharField(max_length=60)),
                ('Telefono', models.IntegerField()),
                ('Correo', models.CharField(max_length=60)),
                ('Ciudad', models.CharField(max_length=60)),
            ],
        ),
    ]
